# Uncomment the next line to define a global platform for your project
platform :ios, '14.2'

target 'Shop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shop
  pod 'Alamofire'
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  `warn_for_unused_master_specs_repo => false`

  target 'ShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShopUITests' do
    # Pods for testing
  end

end
